language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1

before_install:
  - composer self-update

install:
  - travis_retry composer update -n --prefer-dist --prefer-stable

script:
  - vendor/bin/phpunit -v

jobs:
  allow_failures:
    - php: nightly

  include:
    - php: 7.2

    - php: 7.3

    - php: 7.4

    # Test against PHP 8
    - php: nightly

    - stage: Coverage
      php: 7.4
      script:
        - ./vendor/bin/phpunit -v --coverage-clover=coverage.clover
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
